<?php
/**
 * Template Name: Terms of Service
 *
 * @package techorbit-seo
 */
get_header();
$site_name = get_bloginfo( 'name' );
$site_url  = home_url( '/' );
$date      = 'February 23, 2025';
?>

<div class="page-header-vibrant">
    <div class="container">
        <h1 class="page-title-hero">Terms of Service</h1>
        <p class="page-subtitle">Last Updated: <?php echo esc_html( $date ); ?></p>
    </div>
</div>

<div class="page-standard-wrap container">
    <div class="static-page-article">
        <div class="static-page-body single-post-content">

            <p>Please read these Terms of Service ("Terms") carefully before using <strong><?php echo esc_html( $site_name ); ?></strong> at <a href="<?php echo esc_url( $site_url ); ?>"><?php echo esc_url( $site_url ); ?></a> (the "Service") operated by Akeel Khan ("us", "we", or "our").</p>

            <p>By accessing or using our Service, you agree to be bound by these Terms. If you disagree with any part of these Terms, you may not access the Service.</p>

            <h2>1. Use of AI Tools</h2>
            <p>Our AI-powered SEO tools are provided "as is" for informational and productivity purposes. You agree to:</p>
            <ul>
                <li>Use the tools only for lawful purposes</li>
                <li>Not use the tools to generate misleading, deceptive, or harmful content</li>
                <li>Not attempt to reverse-engineer, abuse, or overload our AI API infrastructure</li>
                <li>Take responsibility for reviewing and editing AI-generated content before publishing</li>
                <li>Comply with the terms of service of OpenAI and Google for AI-generated content</li>
            </ul>

            <h2>2. AI Output Disclaimer</h2>
            <p>AI-generated content is provided for reference and productivity purposes only. We do not guarantee the accuracy, completeness, SEO effectiveness, or fitness for any particular purpose of AI outputs. You are solely responsible for verifying and editing any content generated by our tools before use.</p>

            <h2>3. Rate Limits</h2>
            <p>To ensure fair use and prevent API abuse, we limit AI tool usage to 100 requests per hour per IP address. Circumventing this limit (e.g., via VPNs or proxies) is a violation of these Terms and may result in permanent IP-level blocking.</p>

            <h2>4. Intellectual Property</h2>
            <p>The website design, source code, original written content, and branding of <?php echo esc_html( $site_name ); ?> are owned by us and protected by applicable copyright and intellectual property laws. AI-generated outputs do not carry copyright in most jurisdictions — verify your local laws before asserting ownership of AI content.</p>

            <h2>5. Advertising</h2>
            <p>Our website displays third-party advertisements served by Google AdSense. We are not responsible for the content of third-party advertisements. By using our site, you agree to the placement of advertising cookies by Google in your browser.</p>

            <h2>6. Limitation of Liability</h2>
            <p>In no event shall <?php echo esc_html( $site_name ); ?>, its owners, employees, or affiliates be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, or goodwill, arising out of or in connection with your use of our Service.</p>

            <h2>7. Disclaimer of Warranties</h2>
            <p>The Service is provided on an "AS IS" and "AS AVAILABLE" basis, without any warranties of any kind, either express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, or non-infringement.</p>

            <h2>8. Changes to Terms</h2>
            <p>We reserve the right to modify or replace these Terms at any time. We will provide notice of significant changes by updating the "Last Updated" date at the top of this page. Continued use of the Service after changes shall constitute your acceptance of the revised Terms.</p>

            <h2>9. Governing Law</h2>
            <p>These Terms shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law provisions.</p>

            <h2>10. Contact Us</h2>
            <p>If you have questions about these Terms, please contact us through our <a href="<?php echo esc_url( home_url( '/contact/' ) ); ?>">Contact Page</a>.</p>

        </div>
    </div>
</div>

<?php get_footer(); ?>
